services:
  hunter_base:
    build:
      context: .
      dockerfile: Dockerfile.remote
    container_name: hunter-base-service
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: ${PIHOLE_IP}
    environment:
      - TZ=${TZ}
      - CACHE_DB_PATH=/cache/products.db
      - CACHE_TTL_MINUTES=${CACHE_TTL_MINUTES}
    ports:
      - "${HUNTER_PORT}:${HUNTER_PORT}"
    volumes:
      - ${HUNTER_CONFIG_PATH}:/config
      - ${HUNTER_LOGS_PATH}:/logs
      - ${HUNTER_CACHE_PATH}:/cache

networks:
  pihole_net:
    external: true
    name: pihole_net
